### ISSUE TITLE
Port SPIRV patches onto ocl-open-140

### ISSUE THREAD

**Issue by pszymich** [intel/opencl-clang#355]
Hi, there are no SPIRV patches on the ocl-open-140 branch.
Is this expected or are they yet to be ported?

Thanks

**Comment by haonanya** [comment]
Hi, @pszymich. They are not ported yet, I will backport [cl_bf16](https://github.com/intel/opencl-clang/blob/ocl-open-100/patches/spirv/0003-Support-cl_bf16_conversions.patch) patch to SPIRV, since it is on SPIRV main branch. And backport https://github.com/intel/opencl-clang/tree/ocl-open-100/patches/spirv split-barriers-extension-SPV_INTEL to ocl-open-140.
Thanks.

**Comment by haonanya** [comment]
Finished.
