### ISSUE TITLE
question: can we initialize only those LLVM features which we need?

### ISSUE THREAD

**Issue by dvrogozh** [intel/opencl-clang#47]
https://github.com/intel/opencl-clang/blob/a1aed01780ee45a46a3bebef5f75d4a320472b5e/common_clang.cpp#L106

This code attempts to initialize everything in LLVM. As an outcome we are forced to link against almost all the LLVM libraries - see #44 (and a fix in pr #45). Is that possible to reduce the initialization scope? For example, does that make sense to initialize Sparc and other platform parsers?

**Comment by AlexeySachkov** [comment]
We would like to share this library within LLVM community and from this point of view we cannot just initialize `x86` only - this library potentially can be used on different architectures or for cross-compilation.

We could also remove this initialization at all, but in this case we will lose possibility to generate native assembly code instead of LLVM IR.

Since linking issues described in #46 and #44 were resolved, this shouldn't be a problem anymore. So, I would like to close this as won't fix.
